#FT-01 Design home page
chrisostome01/special-tb3 pull request #2
Opened 2022-10-03 13:18 UTC by sezeranoJchrisostome

2022-10-03 13:42 UTC, edson-pro requested changes
DLGTM

2022-10-03 13:42 UTC, edson-pro commented on page/blog-post.html
> +            <div class="logo">
must differentiante footer logo with nav logo

2022-10-03 13:47 UTC, sezeranoJchrisostome commented on page/blog-post.html
> +            <div class="logo">
let me work on that 👍

2022-10-03 14:12 UTC, edson-pro approved these changes

2022-10-03 15:19 UTC, IbrahimBagalwa requested changes
## Great Job @sezeranoJchrisostome 

Great Job keep it up :)
implement the change and re-request the review again. 
### thank you

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    outline: none;
outline none exists in tailwnd ... no need to use it as css

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    @apply text-primary-500 text-[24px] leading-[33.6px] font-bold
this is a custom color no need of this opacity

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    background: radial-gradient(483.9% 2719.65% at -49.5% -250%, #D798E1 17.55%, #9BFFA5 27.56%, #AED3FF 49.89%, #C9D4EF 56.53%, #CACFFA 65.69%);
this is not tailwindcss bro

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    background: radial-gradient(483.9% 2719.65% at -49.5% -250%, #D798E1 17.55%, #9BFFA5 27.56%, #AED3FF 49.89%, #C9D4EF 56.53%, #CACFFA 65.69%);
## css and tailwind combine
you are trying to combine css and tailwind, `background` make this like a custom css

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    border: 1px solid rgb(194, 191, 191)
even here `border`

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    background: linear-gradient(53.94deg, #373FFF 15.02%, #3ACAF8 82.83%);
even here `background`

2022-10-03 15:19 UTC, IbrahimBagalwa commented on style/main.css
> +    border-radius: 24px;
you are using `rounded` and `border-radius` but i think here you are repeating your self. rounded in tailwind it means border-radius in css

2022-10-03 17:20 UTC, IbrahimBagalwa approved these changes
## Great Job @sezeranoJchrisostome 
Keep it up man 👍
LGTM

2022-10-12 05:41 UTC, IbrahimBagalwa requested changes
## Request Changes

apply changes, then re-request for the review.
### thanks

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="section-header">
## wrong name
referring to what the Tech lead told us you cannot have a nested block, is not a good practice here `section-header` in side the `header` try to fix it.

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                <div class="section-header__text">
### same issue 
`section-header__title` `section-header__title--size-large` `section-header__text`
here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="scale-card__item">
## wrong name 
`scale-card__item` you are using the element outside its block.

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="scale-card__item">
### same issue
`scale-card__item` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +        <img class="brand__logo" src="./assets/svgs/brands/brand5.svg" alt="brand icon">
## wrong name
`brand__logo` you are using element outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +        <div class="scale-card">
## prohibition of nested block
`scale-card` nested block is not a good practice

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="section-header section-header--posistion-left">
### same issue
`section-header` `section-header--posistion-left` 
here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                </div>
### same issue
`section-header__higlight` `section-header__title` `section-header__title--size-small`
here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +        <div class="scale-card">
## prohibation nested block
`scale-card` in `scale` make an element of `scale`

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="scale-card__item">
### same issue
`scale-card__item` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                            Sales Tracking
`scale-card__content` `scale-card__title` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="scale-card__item">
`scale-card__item` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                            Project Management
`scale-card__content` `scale-card__title` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +            <div class="scale-card__item">
`scale-card__item` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                    <div class="scale-card__content">
the same issue `scale-card__title` here

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                <img src="./assets/image/ceo.png" class="card__image" alt="user profile">
## naming wrong
you are using `card__image` outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                <img src="./assets/image/marketing.png" class="card__image" alt="user profile">
`card__image` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on index.html
> +                <img src="./assets/image/cto.png" class="card__image" alt="user profile">
`card__image` outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +        <img class="brand__logo" src="../assets/svgs/brands/brand5.svg" alt="brand icon">
## name wrong
`brand__logo` you are using element outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +            <div class="scale-card__text">
`scale-card__text`  you are using an element outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +                <div class="solition__quality-title">
## name wrong
you are using `solition__quality-title` outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +                <div class="solition__description">
`solition__description` here as well

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +            <div class="quality quality--middle">
## prohibation nested block
`quality` nested block is not a good practice

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +                </div>
`solition__quality-title` `solition__description` outside its block

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +            <div class="quality">
## prohibation nested block
`quality` block inside an other block is not a best practice

2022-10-12 05:41 UTC, IbrahimBagalwa commented on page/product.html
> +                </div>
`solition__quality-title` `solition__description` you are using an element ouside its block

2022-10-12 11:20 UTC, edson-pro requested changes
apply the change

2022-10-12 11:20 UTC, edson-pro commented on index.html
> +        <div class="header__links">
change header links div may to to header__nav bcs i thought it was the actual links

2022-10-12 11:20 UTC, edson-pro commented on index.html
> +        <div class="header__content">
change header__content to header__hero may be it can be understandable

2022-10-12 11:20 UTC, edson-pro commented on index.html
> +                <div class="solition__quality-title">
solition__quality-title has no block called like this

2022-10-12 11:20 UTC, edson-pro commented on index.html
> +                <div class="solition__quality-title">
& here

2022-10-12 11:20 UTC, edson-pro commented on index.html
> +                    <div class="footer__copylight">
footer__copylight is not a social link

2022-10-12 11:20 UTC, edson-pro commented on index.html
> +                <div class="social-links">
you started social-links un nesessary brock

2022-10-12 11:29 UTC, sezeranoJchrisostome commented on index.html
> +                <div class="solition__quality-title">
The block is located  to is called solution

2022-10-12 12:51 UTC, IbrahimBagalwa approved these changes
## Great Job @sezeranoJchrisostome 👍 

now it LGTM 👍 
Keep it up :)
### thanks

2022-10-12 13:22 UTC, edson-pro approved these changes
LGTM

2022-10-12 17:26 UTC, sezeranoJchrisostome commented on index.html
> +        <div class="header__content">
header__hero I guess this would would work something like text

2022-10-12 18:33 UTC, musayann requested changes
Looks great, just a couple of issues to address

2022-10-12 18:33 UTC, musayann commented on index.html
> +                    <div class="scale-card__content">
This class name doesn't match the block class name style

2022-10-12 18:33 UTC, musayann commented on index.html
> +                        <div class="scale_card-title">
This class name doesn't match the block class name style

2022-10-13 08:13 UTC, edson-pro approved these changes
GOOD

2022-10-13 08:32 UTC, IbrahimBagalwa approved these changes
## Great Job @sezeranoJchrisostome 👍 

LGTM 👍

2024-02-13 07:44 UTC, merged